/*****************************************************************************************************
// ** Simple Lightbox - 1.07
//    Original source: https://www.w3schools.com/howto/howto_js_lightbox.asp
//    Modified by me to be more responsive, flexible, easier to setup and implement.
//
// ** Create the below thumbnail setup in your HTML, everything else will be generated by Javascript
//    IMPORTANT: link tags <a> need to have class="lightbox-thumbs" to be inserted into Lightbox

<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta charset="utf-8" />
<title>Simple Lightbox demo</title>
<style>
body
{
    font-family:Arial, Helvetica, sans-serif;
    font-size:16px;
}
.lightbox-thumbs
{
    padding-right:25px;
    text-decoration:none;
    border:none;
    cursor:pointer;
}
.lightbox-thumbs img
{
    border:1px #666 solid;
    width:100px;
    height:60px;
}
</style>
<link type="text/css" rel="stylesheet" media="all" href="css/lightbox.css" />
<script type="text/javascript" src="js/lightbox.js"></script>
</head>
<body>
    <div>
        <h3>Simple Lightbox demo</h3>
        <p>Click on an image to open the lightbox</p>
        <a class="lightbox-thumbs" href="img/1.jpg" title="Lights"><img src="img/1.jpg" /></a>
        <a class="lightbox-thumbs" href="img/2.jpg" title="Nature"><img src="img/2.jpg" /></a>
        <a class="lightbox-thumbs" href="img/3.jpg" title="Snow"><img src="img/3.jpg" /></a>
        <a class="lightbox-thumbs" href="img/4.jpg" title="Mountains"><img src="img/4.jpg" /></a>
        <!-- ...more.. -->
    </div>
</body>
</html>
*****************************************************************************************************/

let SimpleLightbox = (function()
{
    'use strict';

    // ** Global variables
    let g_modalPaddingTop = 60;
    let g_slideIndex = 1;
    let g_debug = false;

    // ** Open the Modal
    function openModal()
    {
        document.getElementById('lightbox-modal').style.display = 'block';
        document.getElementsByTagName('body')[0].style.overflow = 'hidden';
    };

    // ** Close the Modal
    function closeModal()
    {
        document.getElementById('lightbox-modal').style.display = 'none';
        document.getElementsByTagName('body')[0].style.overflow = 'auto';
    };

    // ** Next/previous controls
    function nextSlide()
    {
        let slides = document.getElementsByClassName('lightbox-modal-slides');
        let n = g_slideIndex++;
        if (n > slides.length) {g_slideIndex = 1;}
        if (n < 1) {g_slideIndex = slides.length;}
        showSlides(g_slideIndex);
    };
    function prevSlide()
    {
        let slides = document.getElementsByClassName('lightbox-modal-slides');
        let n = g_slideIndex--;
        if (n > slides.length) {g_slideIndex = 1;}
        if (n < 1) {g_slideIndex = slides.length;}
        showSlides(g_slideIndex);
    };

    // ** Thumbnail image controls
    function currentSlide(n)
    {
        showSlides(g_slideIndex = n);
    };

    // ** Work function
    function showSlides(n)
    {
        let i = 0;
        let slides = document.getElementsByClassName('lightbox-modal-slides');
        let thumbs = document.getElementsByClassName('lightbox-modal-thumbs');
        let captionText = document.getElementById('lightbox-modal-caption');

        if (n > slides.length) {g_slideIndex = 1;};
        if (n < 1) {g_slideIndex = slides.length;};

        for (i = 0; i < slides.length; i++)
        {
            slides[i].style.display = 'none';
        }

        for (i = 0; i < thumbs.length; i++)
        {
            thumbs[i].className = thumbs[i].className.replace(' lightbox-modal-active', '');
        }

        slides[g_slideIndex-1].style.display = 'block';
        thumbs[g_slideIndex-1].className += ' lightbox-modal-active';
        captionText.innerHTML = thumbs[g_slideIndex-1].title;
        captionText.innerHTML = captionText.innerHTML.replace(/\\n/g, '<br>');
        captionText.innerHTML = captionText.innerHTML.replace(/\\r\\n/g, '<br>');

        // ** Check imagesize and screensize, make adjustment
        onResize();
    };

    // ** Create modal lightbox
    function createModal()
    {
        let lightboxModal = '<div id="lightbox-modal" class="lightbox-modal-class">' +
                            '   <span class="lightbox-modal-close lightbox-cursor">&times;</span>' +
                            '   <div class="lightbox-modal-content">' +
                            '       <a class="lightbox-modal-prev">&#10094;</a>' +
                            '       <a class="lightbox-modal-next">&#10095;</a>' +
                            '       <div id="lightbox-modal-slides-container"></div>' +
                            '       <div class="lightbox-modal-caption-container">' +
                            '           <p id="lightbox-modal-caption"></p>' +
                            '       </div>' +
                            '       <div id="lightbox-modal-thumbs-container"></div>' +
                            '   </div>'+
                            '</div>';

        // ** Insert into element
        document.getElementsByTagName('body')[0].innerHTML += lightboxModal;

        // ** Create content
        let lightboxThumbs = document.getElementsByClassName('lightbox-thumbs');
        let lightboxSlides = document.getElementById('lightbox-modal-slides-container');
        let lightboxModalThumbs = document.getElementById('lightbox-modal-thumbs-container');

        if(lightboxThumbs[0] && lightboxSlides && lightboxModalThumbs)
        {
            for(let i = 0; i < lightboxThumbs.length;i++)
            {
                let slideNum = i + 1;
                let slideSrc = lightboxThumbs[i].getAttribute('href');
                let slideTitle = lightboxThumbs[i].getAttribute('title');
                let slideThumbSrc = lightboxThumbs[i].getElementsByTagName('img')[0].getAttribute('src');

                let div1 = document.createElement('div');
                div1.setAttribute('class','lightbox-modal-slides');
                lightboxSlides.appendChild(div1);

                let div2 = document.createElement('div');
                div2.setAttribute('class','lightbox-modal-numbertext');
                div1.appendChild(div2);
                div2.innerHTML = slideNum + ' / ' + lightboxThumbs.length;

                let img1 = document.createElement('img');
                img1.setAttribute('src', slideSrc);
                div1.appendChild(img1);

                let div3 = document.createElement('div');
                if(i == lightboxThumbs.length-1)
                {
                    div3.setAttribute('class','lightbox-modal-column-last');
                }
                else
                {
                    div3.setAttribute('class','lightbox-modal-column');
                }
                lightboxModalThumbs.appendChild(div3);

                let img2 = document.createElement('img');
                img2.setAttribute('class', 'lightbox-modal-thumbs');
                img2.setAttribute('title', slideTitle);
                img2.setAttribute('alt', slideNum);
                img2.setAttribute('src', slideThumbSrc);
                div3.appendChild(img2);
            }
        }
        else
        {
            if(g_debug)
            {
                if(!lightboxThumbs[0])
                {
                    console.log('Error, element with class not found: "lightbox-thumbs"');
                }
                if(!lightboxSlides)
                {
                    console.log('Error, element with id not found: "lightbox-modal-slides-container"');
                }
                if(!lightboxModalThumbs)
                {
                    console.log('Error, element with id not found: "lightbox-modal-thumbs-container"');
                }
            }
        }
    };

    // ** Window resize event function
    function onResize()
    {
        let modalPaddingTop = g_modalPaddingTop;
        let slides = document.getElementsByClassName('lightbox-modal-slides');
        let modal = document.getElementsByClassName('lightbox-modal-class');
        let caption = document.getElementsByClassName('lightbox-modal-caption-container');
        let thumbs = document.getElementById('lightbox-modal-thumbs-container');

        if(slides[0] && modal[0] && caption[0] && thumbs)
        {
            for(let i = 0; i < slides.length;i++)
            {
                if(slides[i].style.display == 'block')
                {
                    let img = slides[i].getElementsByTagName('img')[0];
                    let imgHeight = img.offsetHeight;

                    if((imgHeight + (modalPaddingTop * 2)) > window.innerHeight)
                    {
                        modal[0].style.paddingTop = '0';
                        caption[0].style.visibility = 'hidden';
                        thumbs.style.visibility = 'hidden';
                    }
                    else if((imgHeight + (modalPaddingTop * 2)) < window.innerHeight)
                    {
                        modal[0].style.paddingTop = g_modalPaddingTop + 'px';
                        caption[0].style.visibility = 'visible';
                        thumbs.style.visibility = 'visible';
                    }

                    // ** Check for vertical scrollbar, and adjust next button position accordingly
                    let scrollbarWidth = window.innerWidth - modal[0].clientWidth;
                    let next = document.getElementsByClassName('lightbox-modal-next');
                    if (window.innerWidth > modal[0].clientWidth)
                    {
                        if(next[0])
                        {
                            next[0].style.right = scrollbarWidth + 'px';
                        }
                    }
                    else
                    {
                        next[0].style.right = '0';
                    }
                }
            }
        }
    };

    // ** Window load event
    window.addEventListener('load', function(e)
    {
        // ** Create the lightbox modal container
        createModal();

        // ** Closebutton event
        let closeButton = document.getElementsByClassName('lightbox-modal-close');
        if(closeButton[0])
        {
            closeButton[0].addEventListener('click', function()
            {
                closeModal();
            });
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-modal-close"');
            }
        }

        // ** Get all thumbnail elements, class "lightbox-thumbs"
        let thumbs = document.getElementsByClassName('lightbox-thumbs');
        if(thumbs[0])
        {
            for(let i = 0; i < thumbs.length; i++)
            {
                thumbs[i].addEventListener('click', function(e)
                {
                    openModal();
                    currentSlide(i + 1);
                    e.stopPropagation();
                    e.cancelBubble = true;
                    e.preventDefault();
                    return false;
                });
            }
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-thumbs"');
            }
        }

        // ** Get all thumbnail elements in modalbox
        let col = document.getElementsByClassName('lightbox-modal-column');
        if(col[0])
        {
            for(let i = 0; i < col.length; i++)
            {
                col[i].addEventListener('click', function()
                {
                    openModal();
                    currentSlide(col[i].getElementsByTagName('img')[0].getAttribute('alt'));
                });
            }
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-modal-column"');
            }
        }

        // ** Get the last thumbnail element in modalbox
        let col2 = document.getElementsByClassName('lightbox-modal-column-last');
        if(col2[0])
        {
            for(let i = 0; i < col2.length; i++)
            {
                col2[i].addEventListener('click', function()
                {
                    openModal();
                    currentSlide(col2[i].getElementsByTagName('img')[0].getAttribute('alt'));
                });
            }
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-modal-column-last"');
            }
        }

        // ** Previous button event
        let prev = document.getElementsByClassName('lightbox-modal-prev');
        if(prev[0])
        {
            prev[0].addEventListener('click', function()
            {
                prevSlide();
            });
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-modal-prev"');
            }
        }

        // ** Next button event
        let next = document.getElementsByClassName('lightbox-modal-next');
        if(next[0])
        {
            next[0].addEventListener('click', function()
            {
                nextSlide();
            });
        }
        else
        {
            if(g_debug)
            {
                console.log('Error, element with class not found: "lightbox-modal-next"');
            }
        }

        // ** Get key press events
        document.addEventListener('keyup', function(e)
        {
            let keyName = e.key;
            let keyCode = e.code;

            if(keyName == 'ArrowRight' || keyCode == 'ArrowRight')
            {
                nextSlide();
            }
            else if(keyName == 'ArrowLeft' || keyCode == 'ArrowLeft')
            {
                prevSlide();
            }
            else if(keyName == 'Escape' || keyCode == 'Escape')
            {
                closeModal();
            }
            else if(keyName.toLowerCase() == 'x' || keyCode.toLowerCase() == 'x')
            {
                closeModal();
            }
        });

        // ** Window resize event
        window.addEventListener('resize', function()
        {
            onResize();
        });

        // ** Run once on initial load
        onResize();
    });

    return {};
})();
